name: Automated Model Retraining

on:
  schedule:
    # Run daily at 2 AM UTC
    - cron: '0 2 * * *'
  workflow_dispatch:  # Allow manual triggering

permissions:
  contents: write
  pull-requests: write

jobs:
  check-drift:
    runs-on: ubuntu-latest
    outputs:
      needs-retraining: ${{ steps.drift-check.outputs.needs-retraining }}
    steps:
      - name: Checkout code with LFS
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Check for model drift
        id: drift-check
        run: |
          python -c "
          from src.retraining import ModelRetrainingSystem
          system = ModelRetrainingSystem()
          needs_retraining, reason = system.check_performance_drift()
          print(f'needs-retraining={str(needs_retraining).lower()}')
          print(f'reason={reason}')
          " >> $GITHUB_OUTPUT
  retrain-model:
    needs: check-drift
    runs-on: ubuntu-latest
    if: needs.check-drift.outputs.needs-retraining == 'true'
    steps:
      - name: Checkout code with LFS
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies (incl. pytest and git-lfs)
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest
          sudo apt-get update
          sudo apt-get install -y git-lfs
          git lfs install

      - name: Retrain iris and housing models
        run: |
          PYTHONPATH=$(pwd) python src/train.py --task iris
          PYTHONPATH=$(pwd) python src/train.py --task housing

      - name: Run model tests
        run: PYTHONPATH=$(pwd) pytest tests/test_model.py

      - name: Debug: List model directory
        run: ls -lh models/

      - name: Commit and push retrained models with LFS
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # Add exact model and scaler files actually produced
          git add -f models/housing_best_model.pkl \
                  models/housing_scaler.pkl \
                  models/iris_best_model.pkl \
                  models/iris_scaler.pkl \
                  models/scaler.pkl \
                  metrics.json \
                  models/iris_metrics.json || echo "Nothing to add"

          git commit -m "Automated retraining: update model artifacts" || echo "No changes to commit"
          git push origin HEAD:automated-retraining --force-with-lease

      - name: Create pull request with new model
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'Automated model retraining'
          title: 'Automated Model Retraining'
          body: |
            This PR contains an automatically retrained model due to detected performance drift.
            
            Please review the updated model metrics and approve if satisfactory.
          branch: automated-retraining
